version: '3'  #Version of docker compose that we want to use

# Services are sort of like telling a type of container

services:
  redis-server:
    image: 'redis'
  node-app:
    restart: "on-failure"
    build: .  #Look in the current directory and build that file
    ports:
      - "4001:8081" # 8081 on our localmachine to port inside container
